name: pdf
description: Process PDF files - read/extract text and tables, merge, split, rotate, watermark, create, encrypt/decrypt, fill forms, OCR
triggers:
  - pdf
  - read pdf
  - extract pdf
  - merge pdf
  - split pdf
  - create pdf
  - convert pdf
  - pdf text
  - pdf table
  - rotate pdf
  - watermark pdf
  - encrypt pdf
  - fill pdf
  - pdf form
entry_point: main.py
version: 1.0.0
